name: audiobook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - pip:
    - fastapi==0.103.1
    - uvicorn==0.23.2
    - pydantic==2.3.0
    - pydantic-settings==2.0.3
    - python-dotenv==1.0.0
    - pytest==7.4.0
    - httpx==0.24.1
    - pytest-cov==4.1.0